name: prism-public-evaluation
channels: [conda-forge]
dependencies:
  - python=3.12.3
  - numpy=2.3.5
  - scipy=1.17.0
  - pip
  - pip:
      - cupy-cuda12x==13.6.0
      - cvxpy==1.8.1
      - osqp==1.1.0
      - clarabel==0.11.1
